name: cloning repositories
on: [push,pull_request]
jobs: 
  my-job:
   runs-on: windows-latest
   steps:
    - uses: actions/setup-java@v2
      with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '11'
    - name: Setup Python
      uses: actions/setup-python@v2.3.1
      with: 
         python-version: '3.x'
        
    - name: cloning hello-world repository
      uses: actions/checkout@v2.4.0
    - name: cloning second repository
      uses: actions/checkout@v2.4.0
      with:
         repository: vamsibharg/second-repo
         path: second-repo
    - name: looking for java
      run: dir
    - name: run the files    
    - run: |
            cd ${{ github.workspace }}/second-repo/
            dir
    - run: ${{ github.workspace }}\hello.py
    - run: ${{ github.workspace }}\hello.java
    
    
