name: cloning repositories
on: [push,pull_request]
jobs: 
  my-job:
   runs-on: windows-latest
   steps: 
    - name: cloning hello-world repository
      uses: actions/checkout@v2.4.0
      
    - name: looking for files in hello-world
      run: dir
      
    - uses: actions/setup-java@v2
      with:
         distribution: 'zulu' # See 'Supported distributions' for available options
         java-version: '11'
         
    - name: cloning second repository
      uses: actions/checkout@v2.4.0
      with:
         repository: vamsibharg/second-repo
         path: second-repo
   
    - name: looking for files in second-repo  
    - run: |
            cd ${{ github.workspace }}/second-repo/
            dir
    
  
    
    
