name: Manually triggerd workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'getting ID'
        required: true
      
jobs:
  say_hello:
    runs-on: windows-latest
    steps: 
    - run: |
          echo "${{ github.run_id }}!"
        
        
   
