name: Manually triggerd workflow
on:
  workflow_dispatch:
    inputs:
      name:
        description: 'getting ID'
        required: true
        default: github.run_id
jobs:
  say_hello:
    runs-on: windows-latest
    steps: 
    - run: |
          echo "Hello ${{ github.event.inputs.name }}!"
        
        
   
